const foodDatabase = [
  { key: "egg_boiled", name: "Egg Boiled", portion: 38, calories: 54, protein: 5.4, carbs: 0, fat: 3.6 },
  { key: "chicken_breast", name: "Chicken breast (before cooking)", portion: 250, calories: 300, protein: 57.5, carbs: 0, fat: 6.5 },
  { key: "potatoes", name: "Potatoes", portion: 50, calories: 38, protein: 1, carbs: 8.8, fat: 0.1 },
  { key: "cottage_cheese", name: "Cottage cheese", portion: 60, calories: 62, protein: 5.6, carbs: 1.9, fat: 3.6 },
  { key: "basmati_rice", name: "Basmati rice boiled", portion: 100, calories: 131, protein: 3.3, carbs: 28.7, fat: 1.1 },
  { key: "olive_oil", name: "Olive Oil", portion: 5, calories: 41, protein: 0, carbs: 0, fat: 4.6 },
  { key: "tomatoe", name: "Tomatoe", portion: 65, calories: 9, protein: 0.3, carbs: 1.9, fat: 0 },
  { key: "cucmber", name: "Cucmber", portion: 35, calories: 5, protein: 0.3, carbs: 0.5, fat: 0.1 },
  { key: "lettuce", name: "Lettuce", portion: 40, calories: 6, protein: 0.5, carbs: 1.2, fat: 0 },
  { key: "green_pepper", name: "Green pepper", portion: 20, calories: 3, protein: 0.2, carbs: 0.5, fat: 0.1 },
  { key: "lemon", name: "Lemon", portion: 20, calories: 4, protein: 0.2, carbs: 0.6, fat: 0.1 },
  { key: "beans", name: "Beans (cooked fava / ful)", portion: 100, calories: 110, protein: 7.6, carbs: 19.7, fat: 0.4 },
  { key: "bread", name: "Bread (1 loaf Egyptian Baladi/Pita)", portion: 80, calories: 210, protein: 7.2, carbs: 44, fat: 1 },
  { key: "whole_bread", name: "Whole bread (1 slice whole wheat)", portion: 30, calories: 78, protein: 3.8, carbs: 12.5, fat: 1 },
  { key: "yogurt", name: "Yogurt (plain low-fat)", portion: 170, calories: 107, protein: 9, carbs: 11.9, fat: 2.6 },
  { key: "apple", name: "Apple (1 medium)", portion: 180, calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { key: "banana", name: "Banana (1 medium)", portion: 120, calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { key: "peanuts", name: "Peanuts (dry roasted)", portion: 30, calories: 175, protein: 7.3, carbs: 4.8, fat: 14.9 },
  { key: "roumy_cheese", name: "Roumy cheese (1 slice)", portion: 30, calories: 116, protein: 7.1, carbs: 0.5, fat: 9.6 },
  { key: "burger", name: "Burger (beef patty, raw 80/20)", portion: 100, calories: 254, protein: 17.2, carbs: 0, fat: 20 },
  { key: "fish", name: "Fish (tilapia, cooked)", portion: 100, calories: 128, protein: 26.1, carbs: 0, fat: 2.7 },
  { key: "caesar_sauce", name: "Ceaser sauce (1 tbsp)", portion: 15, calories: 78, protein: 0.3, carbs: 0.5, fat: 8.5 },
  { key: "ketchup", name: "Ketchup (1 tbsp)", portion: 15, calories: 17, protein: 0.2, carbs: 4.5, fat: 0.1 },
  { key: "mayo", name: "Mayo (1 tbsp standard)", portion: 14, calories: 94, protein: 0.1, carbs: 0.1, fat: 10.3 },
  { key: "bbq_sauce", name: "BBQ sauce (1 tbsp)", portion: 18, calories: 29, protein: 0.2, carbs: 7, fat: 0.1 },
  { key: "pasta", name: "Pasta (dry weight)", portion: 50, calories: 185, protein: 6.5, carbs: 37, fat: 0.8 }
];